### PR TITLE
[CORE-2255] Move drush from upstream-configuration to root

### PR DESCRIPTION
**Pull request by mbaynton**
tl;dr: Customers are particularly likely to want to upgrade, downgrade,
or remove this component and so should be in the driver's seat.

https://pantheon.slack.com/archives/C1VB1GD3L/p1607633789107400

### CODE REVIEW

**Review by greg-1-anderson — APPROVED** [review]
I think this is best. Putting drush/drush above pantheon-upstreams/upstream-configuration should allow git to resolve merges without conflicts. We should fix this up during limited availability before too many sites have been created; then there shouldn't be too much trouble.

~The alternative would be to put `^8.4 || ^9.7 || ^10` in upstream-configuration/composer.json. This would postpone the problem until Drush 11 came out, which won't be for a while. This will become a bigger inconvenience by then, though. It's best to let the customer decide which version of Drush to require.~

_I see @ari-gold approved the preferred solution in slack._

**Comment by greg-1-anderson** [comment]
Also recording my Slack comment here for reference:

> I was also considering what to do when Drupal 10 comes out. We could bump up to drupal/core-recommended: ^9 || ^10 in the upstream when Pantheon is ready for D10; that would allow customers to pin to 9 in their composer.json if it was necessary for them to do so.
>
> So in short I think it's right to solve these two similar problems in different ways for Drush vs Drupal core.

**Review by alexdicianu — APPROVED** [review]

**Comment by mbaynton** [comment]
Setting to draft because the current change is the _most_ likely to create merge conflicts.

**Comment by mbaynton** [comment]
I did a bit more testing with putting the `drush/drush` line in the `require` section but separated by several lines of whitespace. This did not reliably produce automatically merged new composer.jsons that were also syntactically valid (json's strict rules about commas)

Force-pushed to clean up the commit message and moved the line to the position where it is least likely to generate a merge conflict.

**Comment by mbaynton** [comment]
I think it is more likely than not that @ari-gold wants to do it this way (risking merge conflicts) based on my interpretation of slack; unmarking as draft now that it's as good as it gets.

**Pull request merged**
